---
title: "Nolan Week Four"
author: "Doug Nolan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(knitr)  
library(tidyverse)
library(recipes)
library(caret)
library(mice)
library(moments)
library(forecast)

```



Import data from [Github](https://github.com/bellevue-university/dsc520/blob/master/assignments/version_two/10_11_week/week_04/vgchartz-2024.csv)


```{r import data}
url <- "https://raw.githubusercontent.com/bellevue-university/dsc520/master/assignments/version_two/10_11_week/week_04/vgchartz-2024.csv"

data <- read.csv(url)
## printing out data to validate it matches what is in github
head(data, n = 10)


skewness(data$critic_score, na.rm=TRUE)
skewness(data$total_sales, na.rm=TRUE)
skewness(data$na_sales, na.rm=TRUE)
skewness(data$jp_sales, na.rm=TRUE)
skewness(data$pal_sales, na.rm=TRUE)
skewness(data$other_sales, na.rm=TRUE)
```

```{r fixing skews}
num_cols <- names(data)[sapply(data, is.numeric)]

# fix any skew the best you can
# assuming sales are right skewed
# assuming socres are left skewed
sales_cols <- c("total_sales", "na_sales", "jp_sales", "pal_sales", "other_sales")
score_cols <- c("critic_score")

# fix right skew
for (col in sales_cols) {
  if (col %in% names(data)) {
    data[[col]][data[[col]] < 0] <- 0  
    data[[col]] <- log1p(data[[col]])
  }
}

# fix left skew
for (col in score_cols) {
  if (col %in% names(data)) {
    max_val <- max(data[[col]], na.rm = TRUE)
    flip <- max_val + 1 - data[[col]]
    transformed_flip <- log1p(flip)
    data[[col]] <- max(transformed_flip, na.rm = TRUE) + 1 - transformed_flip  # Reflect back
  }
}
# Summary after skew correction
summary(data[, num_cols])
```


```{r normalize via different techniques}
z_col <- num_cols[1]
minmax_col <- num_cols[2]
pct_col <- num_cols[3]
log_col <- num_cols[4]
rank_col <- num_cols[5]

#apply transformations
data_normalized <- data %>%
  mutate(
    # 1. Z Score
    !!z_col := as.numeric(scale(.data[[z_col]])),
    
    # 2. Min-Max
    !!minmax_col := (.data[[minmax_col]] - min(.data[[minmax_col]], na.rm=TRUE)) /
      (max(.data[[minmax_col]], na.rm=TRUE) - min(.data[[minmax_col]], na.rm=TRUE)),
    
    # 3. Percent Change
    !!pct_col := (.data[[pct_col]] - lag(.data[[pct_col]])) /
      lag(.data[[pct_col]]),
    
    # 4. Log Transform
    !!log_col := log1p(abs(.data[[log_col]])),
    
    # 5. Rank Transform
    !!rank_col := rank(.data[[rank_col]], na.last="keep")
    
  )

#verify results
summary(data_normalized %>% select(all_of(c(
  z_col, minmax_col, pct_col, log_col, rank_col
))))


```

```{r scale numerics}
# select numeric columns
num_cols <- data %>% 
  select(where(is.numeric)) %>% 
  names()
# scale it
data_scaled <- data %>%
  mutate(across(
    all_of(num_cols),
    ~ as.numeric(scale(.))
  ))
# validate it
summary(data_scaled %>% select(all_of(num_cols)))

```

```{r data simulation}
# Validate release_date is Date format
data$release_date <- as.Date(data$release_date)

# Extract existing dates
observed_dates <- data$release_date[!is.na(data$release_date)]

# Simulate missing dates by sampling with replacement
set.seed(123)
data$release_date[is.na(data$release_date)] <- sample(
  observed_dates,
  size = sum(is.na(data$release_date)),
  replace = TRUE
)

# Verify no more nulls
sum(is.na(data$release_date))

```
