---
title: "Nolan_Week_One"
author: "Doug Nolan"
date: "2025-11-30"
output: html_document
---

"Hello World!"
5 + 5

plot(1:10)

5 + 5

"Hello World!"

5
10
25

5 + 5

"Hello World!"
print("Hello World!")

for (x in 1:10) {print(x)}

# this is a comment
"Hello World!"

"Hello World!" # this is a comment

# "Good morning!"
"Good night!"

# this is a comment
# written in
# more than just one line
"Hello World!" 

name <- "Doug"
age <- 35

name # output "Doug"
age # output 35

name <- "Doug Nolan"

name # auto print the value of the name variable

name <- "Doug Nolan" 
print(name)

for (x in 1:10) {print(x)}

text <- "awesome"
paste("R is", text)

text1 <- "R is"
text2 <- "awesome"

paste(text1, text2)

num1 <- 5
num2 <- 10
num1 + num2

num1 + text1


# Assign the same value to multiple variables inn one line
var1 <- var2 <- var3 <- "Orange"

# print variable values
var1
var2
var3

# legal variable names: 
myvar <- "Doug"
my_var <- "Doug"
myVar <- "Doug"
MYVAR <- "Doug"
myvar2 <- "Doug"
.myvar <- "Doug"

# illegal variable names:
2myvar <- "Doug"
my-var <- "Doug"
my var <- "Doug"
_my_var <- "Doug"
my_v@ar <- "Doug"
TRUE <- "Doug"


my_var <- 30 # my_var is type of numeric
my_var <- "Doug" # my_var is now of type character / string

# numeric
x <- 10.5
class(x)

# integer
x <- 1000L
class(x)

# complex
x <- 9i + 3
class(x)

# character / string
x <- "R is exciting"
class(x)

x <- 10.5 # numeric
y <- 10L # integer
z <- 1i #complex


x <- 10.5
y <- 55

# print values of x and y
x
y

# print the class name of x and y
class(x)
class(y)

x <- 1000L
y <- 55L

# print values of x and y
x
y

# print the class name of x and y
class(x)
class(y)


x <- 3+5i
y <- 5i

# print values of x and y
x
y

# print the class name of x and y
class(x)
class(y)

x <- 1L # integer
y <- 2 # numeric

# convert from integer to numeric:
a <- as.numeric(x)

# convert from numeric to integer:
b <- as.integer(y)

# print values of x and y
x
y

# print the class name of a and b
class(a)
class(b)

10 + 5
10 - 5

max(5, 10, 15)
min(5, 10, 15)

sqrt(16)

abs(-4.7)

ceiling(1.4)
floor(1.4)

"hello"
'hello'

str <- "Hello"
str # print the value of str

str <- "Lorem ipsum dolar sit amet,
consectetur adipiscing elit, 
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."

str # print the value of str


cat(str)

str <- "Hello World!"
nchar(str)

grepl("H", str)
grepl("Hello", str)
grepl("X", str)

str1 <- "Hello"
str2 <- "World"
paste(str1, str2)

str <- "We are the so-called "Vikings", from the north."
str

str <- "We are the so-called \"Vikings\", from the north."
str
cat(str)

10 > 9 # true bc 10 is greater than 9
10 == 9 # false bc 10 is not equal to 9
10 < 9 # false bc 10 is greater than 9

a <- 10
b <- 9

a > b

a <- 200
b <- 33

if (b > a) {
print("b is greater than a")
} else {
print("b is not greater than a")
}

10 + 5

my_var <- 3
my_var <<- 3
3 -> my_var
3 ->> my_var

my_var # print my_var


a <- 33
b <- 200

if (b > a) {
  print("b is greater than a")
}

a <- 33
b <- 33

if (b > a) {
  print("b is greater than a")
} else if (a == b) {
  print ("a and b are equal")
}

a <- 200
b <- 33

if (b > a) {
  print("b is greater than a")
} else if (a == b) {
  print ("a and b are equal")
} else {
  print("a is greater than b")
}

a <- 200
b <- 33

if (b > a) {
  print("b is greater than a")
} else {
  print("a is greater than b")
}


x <- 41

if (x > 10) {
  print("Above ten")
  if (x > 20) {
    print("and also above 20!")
  } else{
    print("but not above 20.")
  }
} else {
  print("below 10.")
}

a <- 200
b <- 33
c <- 500

if (a > b & c > a) {
  print("Both conditions are true")
}



if (a > b | c > a) {
  print("Both conditions are true")
}

i <- 1
while (i < 6) {
  print(i)
  i <- i + 1
}


i <- 1
while (i < 6) {
  print(i)
  i <- i + 1
  if (i == 4) {
    break
}
}

i <- 0
while (i < 6) {
  i <- i + 1
  if (i == 3) {
    next
  }
  print(i)
}

dice <-1
while (dice <= 6) {
  if (dice < 6) {
  print("No Yahtzee")
  } else {
    print("Yahtzee!")
  }
  dice <- dice +1
}


for (x in 1:10) {
  print(x)
}

fruits <- list("apple", "banana", "cherry")
for (x in fruits) {
  print(x)
}

dice <- c(1, 2, 3, 4, 5, 6)
for (x in dice) {
  print(x)
}

fruits <- list("apple", "banana", "cherry")
for (x in fruits) {
  if (x == "cherry"){
  break
  }
  print(x)
}

fruits <- list("apple", "banana", "cherry")
for (x in fruits) {
  if (x == "banana"){
  next
  }
  print(x)
}


dice <- 1:6
for (x in dice) {
  if (x == 6) {
  print(paste("The dice number is", x, "Yahtzee!"))
  } else{
    print(paste("The dice number is", x, "Not Yahtzee!"))
}
  
}


adj <- list("red", "big", "tasty")
fruits <- list("apple", "banana", "cherry")
  for (x in adj) {
    for (y in fruits) {
      print(paste(x,y))
}
}


my_function <- function() { # create a function with the name my_function
  print("Hello World!")}
  
my_function()

my_function <- function(fname) {
  paste(fname, "Griffin")
}

my_function("Peter")
my_function("Lois")
my_function("Stewie")

my_function <- function(fname, lname) {
  paste(fname, lname)
}

my_function("Peter", "Griffin")
# Running purposely wrong code breaks R :( 
my_function("Peter")


my_function <- function(country = "Norway") {
  paste("I am from", country)
}

my_function("Sweden")
my_function("India")
my_function() # will get default value of Norway
my_function("USA")


my_function <- function(x) {
  return (5 * x)
}

print(my_function(3))
print(my_function(5))
print(my_function(9))


nested_function <- function(x, y) {
  a <- x + y
  return(a)
}

nested_function(nested_function(2,2), nested_function(3,3))


outer_func <-function(x) {
  inner_func <- function(y) {
    a <- x + y 
    return(a)
  }
  return(inner_func)
}
output <- outer_func(3) # call to outer func
output(5)

tri_recursion <- function(k) {
  if (k > 0) {
    result <- k + tri_recursion(k-1)
    print(result)
  } else {
    result = 0
    return(result)
  }
}
tri_recursion(6)

txt <- "awesome"
my_function <- function() {
  paste("R is", txt)
}
my_function()

txt <- "global variable"
my_function <- function() {
  txt = "fantastic"
  paste("R is", txt)
}
my_function()
txt # print txt

txt <- "global variable"
my_function <- function() {
  txt <<- "fantastic"
  paste("R is", txt)
}
my_function()
print(txt) # print txt


txt <- "awesome"
my_function <- function() {
  txt <<- "fantastic"
  paste("R is", txt)
}

my_function()

paste("R is", txt)

