---
title: "Nolan_Week_Six_Part_Two"
author: "Doug Nolan"
date: "`1-27-2026`"
output: html_document
---

```{r exercise 2}

data = ("
        Social  Higher  Lower
        Y 1 120
        N 118 2")

data_as_matrix <- as.matrix(read.table(textConnection(data),
               header=TRUE,
               row.names=1))
fisher.test(data_as_matrix)



```


- null hypothesis is using social does not result in lower cognitive ability. alpha = .05
- alternative hypothesis 
- p value < 2.2e-16
- reject null hypothesis . data suggests using social media is associated with lower cognitive ability
- one sided test - we only looked at if the cognitive ability was lower. 



```{r coin toss}
# toss a 2 sided coin 100 times, null hypothesis is that the coins is fair. Alpha = .05


binom.test(95, 100, p=0.5)


```
- alternative hypothesis is the coin is NOT fair. P(heads) <> .5 
- p value of coin showing up 95/100 times = p-value < 2.2e-16
- reject the null hypothesis, the coin is not fair with these results
- this is a two sided test, because deviation high or low matters. 

```{r ch 10 exercise 1}
library(cowplot)
library(ggplot2)
library(glue)
library(pracma)
library(reshape)
library(scales)
library(truncnorm)

# p value input GOES HERE
pval <- .025
# create a Gaussian probability curve
zvals <- seq(-3, 3, length=1001)
zpdf <- dnorm(zvals)

# plot the probability function and the vertical lines
df1 <- data.frame(x=zvals, y=zpdf)
fig_A <- ggplot(df1, aes(x=x, y=y)) +
           geom_smooth(color="black") +
           scale_x_continuous(limit=c(head(zvals, 1), tail(zvals, 1)), expand=c(0, 0)) +
           scale_y_continuous(limit=c(0, .42), breaks=NULL, expand=c(0, 0)) +
           labs(x="", y=expression(paste("Prob. given ", "H"[0]))) +
           theme_classic()

# two-tailed p-values
mn_idx <- which.min(zvals**2)
pvalsL <- pnorm(zvals[1:mn_idx])
pvalsR <- 1 - pnorm(zvals[(mn_idx+1):length(zvals)])
pvals2 <- 2 * c(pvalsL, pvalsR)

# plot the probability function
df2 <- data.frame(x=zvals, y=pvals2)
fig_B <- ggplot(df2, aes(x=x, y=y)) +
           geom_line(color="black") +
           geom_hline(yintercept=pval, color="gray50", linetype="dashed") +
           scale_x_continuous(limit=c(head(zvals, 1), tail(zvals, 1)), expand=c(0, 0)) +
           labs(x="", y="P-value") +
           theme_classic()

# draw vertical lines
zcrit_low <- qnorm(pval/2)
zcrit_high <- qnorm(1 - pval/2)

vline1 <- geom_vline(aes(xintercept=zvals[which.min((zvals-zcrit_low)**2)]), color="darkgray",
                     linetype="dotted", linewidth=.75)
vline2 <- geom_vline(aes(xintercept=zvals[which.min((zvals-zcrit_high)**2)]), color="darkgray",
                     linetype="dotted", linewidth=.75)
fig_A <- fig_A + vline1 + vline2
fig_B <- fig_B + vline1 + vline2

# draw patches for significant regions
zidx <- which.min((zvals-zcrit_low)**2)
fig_A <- fig_A + geom_ribbon(data=subset(df1, x <= x[zidx]), aes(ymin=0, ymax=y), alpha=.4)
fig_B <- fig_B + geom_ribbon(data=subset(df2, x <= x[zidx]), aes(ymin=0, ymax=y), alpha=.4)

zidx <- which.min((zvals-zcrit_high)**2)
fig_A <- fig_A + geom_ribbon(data=subset(df1, x >= x[zidx]), aes(ymin=0, ymax=y), alpha=.4)
fig_B <- fig_B + geom_ribbon(data=subset(df2, x >= x[zidx]), aes(ymin=0, ymax=y), alpha=.4)

fig_C <- fig_B

# indicators
fig_A <- fig_A + annotate("text", x=0, y=.3, label='\"Not Significant\"') +
  annotate("segment", x=-2.35, xend=-2.2, y=.12, yend=.05, lwd=1.25, linejoin="mitre",
           arrow=arrow(type="closed", length=unit(.02, "npc"))) +
  annotate("text", x=-2.375, y=.15, label='\"Significant\"') +
  annotate("segment", x=2.35, xend=2.2, y=.12, yend=.05, lwd=1.25, linejoin="mitre",
           arrow=arrow(type="closed", length=unit(.02, "npc"))) +
  annotate("text", x=2.375, y=.15, label='\"Significant\"')

#fig_B <- fig_B + annotate("text", x=2.4, y=.12, label="p=.05")
#fig_C <- fig_C + annotate("text", x=2.4, y=.0975, label="p=.05")
fig_B <- fig_B + annotate("text", x=2.4, y=pval + .02, label=paste0("p=", pval))
fig_C <- fig_C + annotate("text", x=2.4, y=pval, label=paste0("p=", pval))

# panel titles
fig_A <- fig_A + ggtitle(expression(paste(bold("A)  "), "Test statistic distribution if ", "H"[0], " were true")))
fig_B <- fig_B + ggtitle(expression(paste(bold("B)  "), "P-value for each test statistic")))
fig_C <- fig_C + ggtitle(expression(paste(bold("C)  "), "Same as panel ", bold("B"), " but in log scale")))

fig_B <- fig_B + scale_y_continuous(limits=c(0, 1.03), breaks=seq(0, 1, .5), expand=c(0, 0))
fig_C <- fig_C + xlab("Test statistic (z-score)") +
           scale_y_log10(labels=trans_format("log10", math_format(10^.x))) +
           annotation_logticks(sides="l", outside=TRUE, size=.25,
                               short=unit(.075, "cm"), mid=unit(.125, "cm"), long=unit(.175, "cm")) +
           coord_cartesian(clip="off") +
           theme(axis.ticks.y=element_blank())

fig <- plot_grid(fig_A, fig_B, fig_C, ncol=1, align="v", axis="l")

fig
ggsave(filename="hyp_sigRegionsZandP.png", width=7, height=7, units="in", dpi=300)


```
